config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :users, only: [:show, :edit, :create, :update] do
    get '/edit-categories', to: 'categories#edit'
    patch '/edit-categories', to: 'categories#edit'
    resources :categories, only: [:new, :create, :update, :destroy]
    resources :expenses, only: [:new, :edit, :create, :update, :destroy]
  end
  # Sessions Resources
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
  has_many :expenses
  validates :name, :user_id, presence: true
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  belongs_to :frequency
  validates :name, :amount, :user_id, :category_id,
            :frequency_id, presence: true

end

app/models/frequency.rb
class Frequency < ActiveRecord::Base
  has_many :expenses
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :expenses
  has_many :categories
  accepts_nested_attributes_for :categories, allow_destroy: true
  has_secure_password validations: false
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
  validates :password, on: :create, presence: true, length: { minimum: 6 }
  validates :password, on: :update, allow_blank: true, length: { minimum: 6 }

  def getting_started
    # Create 5 Starter Categories
    starter_cats = %w(Insurance\ Premiums Vacations Car\ Repairs Tech\ Upgrades Gifts)
    starter_cats.each do |cat|
      self.categories.create(name: cat)
    end

    # Inject an expense into each category
    self.categories.
      find_by(name: 'Insurance Premiums').
      expenses.create(name: 'Auto Insurance', amount: 600, frequency_id: 5, user_id: self.id)
    self.categories.
      find_by(name: 'Insurance Premiums').
      expenses.create(name: 'Life Insurance', amount: 480, frequency_id: 2, user_id: self.id)
    self.categories.
      find_by(name: 'Vacations').
      expenses.create(name: 'Visit the in-laws', amount: 750, frequency_id: 2, user_id: self.id)
    self.categories.
      find_by(name: 'Car Repairs').
      expenses.create(name: 'New Tires', amount: 500, frequency_id: 7, user_id: self.id)
    self.categories.
      find_by(name: 'Tech Upgrades').
      expenses.create(name: 'New Macbook', amount: 1500, frequency_id: 8, user_id: self.id)
    self.categories.
      find_by(name: 'Tech Upgrades').
      expenses.create(name: 'New Smartphone', amount: 800, frequency_id: 7, user_id: self.id)
    self.categories.
      find_by(name: 'Gifts').
      expenses.create(name: 'Christmas', amount: 1000, frequency_id: 2, user_id: self.id)
    self.categories.
      find_by(name: 'Gifts').
      expenses.create(name: 'All Birthdays', amount: 400, frequency_id: 2, user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user || User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def access_denied
    if @user != current_user
      flash[:error] = 'You can not do that.'
      redirect_to root_url
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_user, only: [:new, :edit]
  before_action :require_user, only: [:new, :edit]

  def new
    @category = Category.new
  end

  def edit
    if request.patch?
      if @user.update(user_params)
        flash[:success] = 'Categories Updated'
        redirect_to user_path(@user)
      else
        render :edit
      end
    end
  end

  def create
    @user = User.find(params[:user_id])
    @category = @user.categories.new(category_params)
    if @category.save
      flash[:success] = 'New Category Created'
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update
  end

  def destroy
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end

    def user_params
      params.require(:user).permit(categories_attributes: [:id, :name, :_destroy])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    def require_user
      if @user != current_user
        flash[:error] = 'You can not do that.'
        redirect_to root_url
      end
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_user, only: [:new, :edit, :create, :update, :destroy]
  before_action :require_user, only: [:new, :create, :destroy]
  before_action :set_expense, only: [:edit, :update, :destroy]

  def new
    @expense = Expense.new
  end

  def edit
  end

  def create
    @expense = @user.expenses.new(expense_params)
    if @expense.save
      flash[:success] = 'New Expense Created'
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update
    if @expense.update(expense_params)
      flash[:success] = 'Expense Successfully Updated'
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    if @user.expenses.destroy(@expense)
      flash[:success] = 'Expense Deleted'
      redirect_to user_path(@user)
    else
      flash[:error] = 'Something went wrong'
      redirect_to user_path(@user)
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :frequency_id,
                                   :category_id)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def require_user
    access_denied
  end

  def set_expense
    @expense = Expense.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user.valid? && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = 'Your are logged in.'
      redirect_to user_path(@user)
    else
      flash[:error] = 'Oops. That is not right'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  before_action :require_user, only: [:show]

  def show
    @category = @user.categories.first
  end

  def new
    if current_user
      redirect_to user_path(current_user)
    end
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.getting_started
      flash[:success] = 'Your account has been created!  A few categories and expenses have been added to help get you started.  You can add additional categories and expenses by using the links at the top of the screen. Enjoy!'
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def update; end

  private

    def user_params
      params.require(:user).permit(:email, :password)
    end

    def set_user
      @user = User.find(params[:id])
    end

    def require_user
      if @user != current_user
        flash[:error] = 'You can not do that.'
        redirect_to root_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<%= render 'shared/form_error', error_object: @user %>
<h1>Edit Categories</h1>
<p>A category must be empty to be deleted</p>
<%= form_for @user, url: user_edit_categories_path, method: 'patch' do |f| %>
  <%= f.fields_for :categories do |categories_form| %>
    <div class='form-inline form-group' >
      <div class='form-group'>
        <%= categories_form.text_field :name, class: 'form-control' %>
      </div>
      <% if categories_form.object.expenses.empty? %>
        <div class='checkbox'>
          <%= categories_form.check_box :_destroy %> Delete
        </div>
      <% end %>
    </div>
  <% end %>
  <%= f.submit 'Update Categories', class: 'btn btn-success' %>
<% end %>

app/views/categories/new.html.erb
<%= render 'shared/form_error', error_object: @category %>
<div class='row'>
  <div class='col-xs-12'>
    <h1>Create a new category</h1>
  </div>
</div>
<div class='row'>
  <div class='col-xs-4'>
    <%= form_for [@user, @category] do |f| %>
      <div class="form-group">
        <%= f.label :name, 'Category Name' %>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Category Name' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-success' %>
    <% end %>
  </div>

app/views/expenses/_form.html.erb
<%= render 'shared/form_error', error_object: @expense %>
<%= form_for [@user, @expense],
             html: {class: 'form-horizontal'} do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Expense', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :amount, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :amount, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :frequency_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.collection_select(:frequency_id, Frequency.all.sort_by { |freq| freq.value }.reverse, :id, :name, {}, { class: 'form-control'}) %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :category_id, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.collection_select(:category_id, @user.categories, :id, :name, {}, { class: 'form-control'}) %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit @expense.id ? 'Edit Expense' : 'Add Expense', class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<%= render 'form' %>

app/views/expenses/new.html.erb
<%= render 'form' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "success" ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if @page_title.present? %>
      <%= "#{@page_title} | BudgetStart" %>
    <% else %>
      <%= 'BudgetStart' %>
    <% end %>
  </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">BudgetStart</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if logged_in? %>
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'Add Expense', new_user_expense_path(@user) %></li>
            <li><%= link_to 'Add Category', new_user_category_path(@user) %></li>
            <li><%= link_to 'Edit Categores', user_edit_categories_path(@user) %></li>
            <li><a href="/logout">Logout</a></li>
          <% else %>
            <li><a href="/login">Login</a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_form_error.html.erb
<% if error_object.errors.any? %>
  <div class='row'>
    <div class="col-md-6 col-md-offset-3 alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"
              aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4>Please fix the following errors: </h4>
      <ul class='list-unstyled'>
        <% error_object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<div class='jumbotron'>
  <% @page_title = 'Irregular Expense Budgeting' %>
  <div class='row text-center'>
    <div class='col-xs-12'>
      <h1>Welcome to BudgetStart</h1>
      <h3>Irregular Expenses Derail Your Budget. I can help</h3>
    </div>
    <div class='col-xs-12 margin-15px015px0'>
      <%= render 'shared/form_error', error_object: @user %>
      <%= form_for @user, html: { class: 'form-inline'} do |f| %>
        <div class="form-group">
          <%= f.label :email, class: 'sr-only' %>
          <%= f.email_field :email, class: 'form-control', placeholder: 'Email' %>
        </div>
        <div class="form-group">
          <%= f.label :password, class: 'sr-only' %>
          <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
        </div>
        <%= f.submit 'join', class: 'btn btn-success' %>
      <% end %>
    </div>
    <div class='col-xs-12'>
      Already a member? <%= link_to 'login', '#' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% @user.categories.each do |category| %>
  <% count = 1 %>
  <% monthly_total = 0.00 %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class='panel-title'><%= category.name %></h3>
    </div>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Expense</th>
            <th>Amount</th>
            <th>Frequency</th>
            <th>Monthly Budget</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @user.expenses.where(category_id: category).each do |expense| %>
            <tr>
              <th scope="row"><%= count %></th>
              <td><%= expense.name %></td>
              <td>$<%= expense.amount %></td>
              <td><%= expense.frequency.name %></td>
              <% monthly_expense = (expense.amount * expense.frequency.value / 12) %>
              <% monthly_total += monthly_expense %>
              <td>$<%= "#{(expense.amount * expense.frequency.value / 12).round}" %></td>
              <td><%= link_to 'edit', edit_user_expense_path(@user, expense) %></td>
              <td><%= link_to 'delete', user_expense_path(@user, expense), method: :delete %></td>
            </tr>
            <% count += 1 %>
          <% end %>
        </tbody>
      </table>
      <div class="panel-footer">Monthly Total: $<%= monthly_total.round %> </div>
  </div>
<% end %>